// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sumpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SumServiceClient is the client API for SumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SumServiceClient interface {
	// Unary API
	Sum(ctx context.Context, in *Arguments, opts ...grpc.CallOption) (*Result, error)
	BiDiSum(ctx context.Context, opts ...grpc.CallOption) (SumService_BiDiSumClient, error)
}

type sumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSumServiceClient(cc grpc.ClientConnInterface) SumServiceClient {
	return &sumServiceClient{cc}
}

func (c *sumServiceClient) Sum(ctx context.Context, in *Arguments, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/greet.SumService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sumServiceClient) BiDiSum(ctx context.Context, opts ...grpc.CallOption) (SumService_BiDiSumClient, error) {
	stream, err := c.cc.NewStream(ctx, &SumService_ServiceDesc.Streams[0], "/greet.SumService/BiDiSum", opts...)
	if err != nil {
		return nil, err
	}
	x := &sumServiceBiDiSumClient{stream}
	return x, nil
}

type SumService_BiDiSumClient interface {
	Send(*Arguments) error
	Recv() (*Result, error)
	grpc.ClientStream
}

type sumServiceBiDiSumClient struct {
	grpc.ClientStream
}

func (x *sumServiceBiDiSumClient) Send(m *Arguments) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sumServiceBiDiSumClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SumServiceServer is the server API for SumService service.
// All implementations must embed UnimplementedSumServiceServer
// for forward compatibility
type SumServiceServer interface {
	// Unary API
	Sum(context.Context, *Arguments) (*Result, error)
	BiDiSum(SumService_BiDiSumServer) error
	mustEmbedUnimplementedSumServiceServer()
}

// UnimplementedSumServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSumServiceServer struct {
}

func (UnimplementedSumServiceServer) Sum(context.Context, *Arguments) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedSumServiceServer) BiDiSum(SumService_BiDiSumServer) error {
	return status.Errorf(codes.Unimplemented, "method BiDiSum not implemented")
}
func (UnimplementedSumServiceServer) mustEmbedUnimplementedSumServiceServer() {}

// UnsafeSumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SumServiceServer will
// result in compilation errors.
type UnsafeSumServiceServer interface {
	mustEmbedUnimplementedSumServiceServer()
}

func RegisterSumServiceServer(s grpc.ServiceRegistrar, srv SumServiceServer) {
	s.RegisterService(&SumService_ServiceDesc, srv)
}

func _SumService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.SumService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumServiceServer).Sum(ctx, req.(*Arguments))
	}
	return interceptor(ctx, in, info, handler)
}

func _SumService_BiDiSum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SumServiceServer).BiDiSum(&sumServiceBiDiSumServer{stream})
}

type SumService_BiDiSumServer interface {
	Send(*Result) error
	Recv() (*Arguments, error)
	grpc.ServerStream
}

type sumServiceBiDiSumServer struct {
	grpc.ServerStream
}

func (x *sumServiceBiDiSumServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sumServiceBiDiSumServer) Recv() (*Arguments, error) {
	m := new(Arguments)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SumService_ServiceDesc is the grpc.ServiceDesc for SumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet.SumService",
	HandlerType: (*SumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SumService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BiDiSum",
			Handler:       _SumService_BiDiSum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sumpb/sumpb.proto",
}
