// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: sumpb/sumpb.proto

package sumpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Arguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArgumentA int32 `protobuf:"varint,1,opt,name=argument_a,json=argumentA,proto3" json:"argument_a,omitempty"`
	ArgumentB int32 `protobuf:"varint,2,opt,name=argument_b,json=argumentB,proto3" json:"argument_b,omitempty"`
}

func (x *Arguments) Reset() {
	*x = Arguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sumpb_sumpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arguments) ProtoMessage() {}

func (x *Arguments) ProtoReflect() protoreflect.Message {
	mi := &file_sumpb_sumpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arguments.ProtoReflect.Descriptor instead.
func (*Arguments) Descriptor() ([]byte, []int) {
	return file_sumpb_sumpb_proto_rawDescGZIP(), []int{0}
}

func (x *Arguments) GetArgumentA() int32 {
	if x != nil {
		return x.ArgumentA
	}
	return 0
}

func (x *Arguments) GetArgumentB() int32 {
	if x != nil {
		return x.ArgumentB
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum int32 `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sumpb_sumpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_sumpb_sumpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_sumpb_sumpb_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_sumpb_sumpb_proto protoreflect.FileDescriptor

var file_sumpb_sumpb_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x75, 0x6d, 0x70, 0x62, 0x2f, 0x73, 0x75, 0x6d, 0x70, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x65, 0x65, 0x74, 0x22, 0x49, 0x0a, 0x09, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x72, 0x67,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x42, 0x22, 0x1a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x75,
	0x6d, 0x32, 0x68, 0x0a, 0x0a, 0x53, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x28, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x41,
	0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x07, 0x42, 0x69, 0x44,
	0x69, 0x53, 0x75, 0x6d, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x41, 0x72, 0x67,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x2f, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2f, 0x73, 0x75, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sumpb_sumpb_proto_rawDescOnce sync.Once
	file_sumpb_sumpb_proto_rawDescData = file_sumpb_sumpb_proto_rawDesc
)

func file_sumpb_sumpb_proto_rawDescGZIP() []byte {
	file_sumpb_sumpb_proto_rawDescOnce.Do(func() {
		file_sumpb_sumpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_sumpb_sumpb_proto_rawDescData)
	})
	return file_sumpb_sumpb_proto_rawDescData
}

var file_sumpb_sumpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sumpb_sumpb_proto_goTypes = []interface{}{
	(*Arguments)(nil), // 0: greet.Arguments
	(*Result)(nil),    // 1: greet.Result
}
var file_sumpb_sumpb_proto_depIdxs = []int32{
	0, // 0: greet.SumService.Sum:input_type -> greet.Arguments
	0, // 1: greet.SumService.BiDiSum:input_type -> greet.Arguments
	1, // 2: greet.SumService.Sum:output_type -> greet.Result
	1, // 3: greet.SumService.BiDiSum:output_type -> greet.Result
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sumpb_sumpb_proto_init() }
func file_sumpb_sumpb_proto_init() {
	if File_sumpb_sumpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sumpb_sumpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sumpb_sumpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sumpb_sumpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sumpb_sumpb_proto_goTypes,
		DependencyIndexes: file_sumpb_sumpb_proto_depIdxs,
		MessageInfos:      file_sumpb_sumpb_proto_msgTypes,
	}.Build()
	File_sumpb_sumpb_proto = out.File
	file_sumpb_sumpb_proto_rawDesc = nil
	file_sumpb_sumpb_proto_goTypes = nil
	file_sumpb_sumpb_proto_depIdxs = nil
}
